core/config/routes.rb
Rails.application.routes.draw do
  resources :core_stuffs, :path => ''
end

core/app/models/core_stuff.rb
class CoreStuff < ActiveRecord::Base
end

core/app/controllers/core_stuffs_controller.rb
class CoreStuffsController < ApplicationController
  before_action :set_core_stuff, only: [:show, :edit, :update, :destroy]

  # GET /core_stuffs
  def index
    @core_stuffs = CoreStuff.all
  end

  # GET /core_stuffs/1
  def show
  end

  # GET /core_stuffs/new
  def new
    @core_stuff = CoreStuff.new
  end

  # GET /core_stuffs/1/edit
  def edit
  end

  # POST /core_stuffs
  def create
    @core_stuff = CoreStuff.new(core_stuff_params)

    if @core_stuff.save
      redirect_to @core_stuff, notice: 'Core stuff was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /core_stuffs/1
  def update
    if @core_stuff.update(core_stuff_params)
      redirect_to @core_stuff, notice: 'Core stuff was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /core_stuffs/1
  def destroy
    @core_stuff.destroy
    redirect_to core_stuffs_url, notice: 'Core stuff was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_core_stuff
      @core_stuff = CoreStuff.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def core_stuff_params
      params.require(:core_stuff).permit(:core)
    end
end

core/app/helpers/core_stuffs_helper.rb
module CoreStuffsHelper
end

core/app/views/core_stuffs/_form.html.erb
<%= form_for(@core_stuff) do |f| %>
  <% if @core_stuff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@core_stuff.errors.count, "error") %> prohibited this core_stuff from being saved:</h2>

      <ul>
      <% @core_stuff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :core %><br>
    <%= f.text_field :core %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

core/app/views/core_stuffs/edit.html.erb
<h1>Editing Core Stuff</h1>

<%= render 'form' %>

<%= link_to 'Show', @core_stuff %> |
<%= link_to 'Back', core_stuffs_path %>

core/app/views/core_stuffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Core Stuffs</h1>

<table>
  <thead>
    <tr>
      <th>Core</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @core_stuffs.each do |core_stuff| %>
      <tr>
        <td><%= core_stuff.core %></td>
        <td><%= link_to 'Show', core_stuff %></td>
        <td><%= link_to 'Edit', edit_core_stuff_path(core_stuff) %></td>
        <td><%= link_to 'Destroy', core_stuff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Core stuff', new_core_stuff_path %>

core/app/views/core_stuffs/new.html.erb
<h1>New Core Stuff</h1>

<%= render 'form' %>

<%= link_to 'Back', core_stuffs_path %>

core/app/views/core_stuffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Core:</strong>
  <%= @core_stuff.core %>
</p>

<%= link_to 'Edit', edit_core_stuff_path(@core_stuff) %> |
<%= link_to 'Back', core_stuffs_path %>