shop/config/routes.rb
Rails.application.routes.draw do
  resources :shop_stuffs
end

shop/app/models/shop_stuff.rb
class ShopStuff < ActiveRecord::Base
end

shop/app/controllers/shop_stuffs_controller.rb
class ShopStuffsController < ApplicationController
  before_action :set_shop_stuff, only: [:show, :edit, :update, :destroy]

  # GET /shop_stuffs
  def index
    @shop_stuffs = ShopStuff.all
  end

  # GET /shop_stuffs/1
  def show
  end

  # GET /shop_stuffs/new
  def new
    @shop_stuff = ShopStuff.new
  end

  # GET /shop_stuffs/1/edit
  def edit
  end

  # POST /shop_stuffs
  def create
    @shop_stuff = ShopStuff.new(shop_stuff_params)

    if @shop_stuff.save
      redirect_to @shop_stuff, notice: 'Shop stuff was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /shop_stuffs/1
  def update
    if @shop_stuff.update(shop_stuff_params)
      redirect_to @shop_stuff, notice: 'Shop stuff was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /shop_stuffs/1
  def destroy
    @shop_stuff.destroy
    redirect_to shop_stuffs_url, notice: 'Shop stuff was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop_stuff
      @shop_stuff = ShopStuff.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def shop_stuff_params
      params.require(:shop_stuff).permit(:shop)
    end
end

shop/app/helpers/shop_stuffs_helper.rb
module ShopStuffsHelper
end

shop/app/views/shop_stuffs/_form.html.erb
<%= form_for(@shop_stuff) do |f| %>
  <% if @shop_stuff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop_stuff.errors.count, "error") %> prohibited this shop_stuff from being saved:</h2>

      <ul>
      <% @shop_stuff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shop %><br>
    <%= f.text_field :shop %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

shop/app/views/shop_stuffs/edit.html.erb
<h1>Editing Shop Stuff</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop_stuff %> |
<%= link_to 'Back', shop_stuffs_path %>

shop/app/views/shop_stuffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shop Stuffs</h1>

<table>
  <thead>
    <tr>
      <th>Shop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shop_stuffs.each do |shop_stuff| %>
      <tr>
        <td><%= shop_stuff.shop %></td>
        <td><%= link_to 'Show', shop_stuff %></td>
        <td><%= link_to 'Edit', edit_shop_stuff_path(shop_stuff) %></td>
        <td><%= link_to 'Destroy', shop_stuff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop stuff', new_shop_stuff_path %>

shop/app/views/shop_stuffs/new.html.erb
<h1>New Shop Stuff</h1>

<%= render 'form' %>

<%= link_to 'Back', shop_stuffs_path %>

shop/app/views/shop_stuffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shop:</strong>
  <%= @shop_stuff.shop %>
</p>

<%= link_to 'Edit', edit_shop_stuff_path(@shop_stuff) %> |
<%= link_to 'Back', shop_stuffs_path %>