tree/config/routes.rb
Rails.application.routes.draw do
  resources :tree_stuffs
end

tree/app/models/tree_stuff.rb
class TreeStuff < ActiveRecord::Base
end

tree/app/controllers/tree_stuffs_controller.rb
class TreeStuffsController < ApplicationController
  before_action :set_tree_stuff, only: [:show, :edit, :update, :destroy]

  # GET /tree_stuffs
  def index
    @tree_stuffs = TreeStuff.all
  end

  # GET /tree_stuffs/1
  def show
  end

  # GET /tree_stuffs/new
  def new
    @tree_stuff = TreeStuff.new
  end

  # GET /tree_stuffs/1/edit
  def edit
  end

  # POST /tree_stuffs
  def create
    @tree_stuff = TreeStuff.new(tree_stuff_params)

    if @tree_stuff.save
      redirect_to @tree_stuff, notice: 'Tree stuff was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tree_stuffs/1
  def update
    if @tree_stuff.update(tree_stuff_params)
      redirect_to @tree_stuff, notice: 'Tree stuff was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tree_stuffs/1
  def destroy
    @tree_stuff.destroy
    redirect_to tree_stuffs_url, notice: 'Tree stuff was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree_stuff
      @tree_stuff = TreeStuff.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tree_stuff_params
      params.require(:tree_stuff).permit(:tree)
    end
end

tree/app/helpers/tree_stuffs_helper.rb
module TreeStuffsHelper
end

tree/app/views/tree_stuffs/_form.html.erb
<%= form_for(@tree_stuff) do |f| %>
  <% if @tree_stuff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tree_stuff.errors.count, "error") %> prohibited this tree_stuff from being saved:</h2>

      <ul>
      <% @tree_stuff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tree %><br>
    <%= f.text_field :tree %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tree/app/views/tree_stuffs/edit.html.erb
<h1>Editing Tree Stuff</h1>

<%= render 'form' %>

<%= link_to 'Show', @tree_stuff %> |
<%= link_to 'Back', tree_stuffs_path %>

tree/app/views/tree_stuffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tree Stuffs</h1>

<table>
  <thead>
    <tr>
      <th>Tree</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tree_stuffs.each do |tree_stuff| %>
      <tr>
        <td><%= tree_stuff.tree %></td>
        <td><%= link_to 'Show', tree_stuff %></td>
        <td><%= link_to 'Edit', edit_tree_stuff_path(tree_stuff) %></td>
        <td><%= link_to 'Destroy', tree_stuff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tree stuff', new_tree_stuff_path %>

tree/app/views/tree_stuffs/new.html.erb
<h1>New Tree Stuff</h1>

<%= render 'form' %>

<%= link_to 'Back', tree_stuffs_path %>

tree/app/views/tree_stuffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tree:</strong>
  <%= @tree_stuff.tree %>
</p>

<%= link_to 'Edit', edit_tree_stuff_path(@tree_stuff) %> |
<%= link_to 'Back', tree_stuffs_path %>