frontend/config/routes.rb
Rails.application.routes.draw do
  resources :front_stuffs
end

frontend/app/models/front_stuff.rb
class FrontStuff < ActiveRecord::Base
end

frontend/app/controllers/front_stuffs_controller.rb
class FrontStuffsController < ApplicationController
  before_action :set_front_stuff, only: [:show, :edit, :update, :destroy]

  # GET /front_stuffs
  def index
    @front_stuffs = FrontStuff.all
  end

  # GET /front_stuffs/1
  def show
  end

  # GET /front_stuffs/new
  def new
    @front_stuff = FrontStuff.new
  end

  # GET /front_stuffs/1/edit
  def edit
  end

  # POST /front_stuffs
  def create
    @front_stuff = FrontStuff.new(front_stuff_params)

    if @front_stuff.save
      redirect_to @front_stuff, notice: 'Front stuff was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /front_stuffs/1
  def update
    if @front_stuff.update(front_stuff_params)
      redirect_to @front_stuff, notice: 'Front stuff was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /front_stuffs/1
  def destroy
    @front_stuff.destroy
    redirect_to front_stuffs_url, notice: 'Front stuff was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_front_stuff
      @front_stuff = FrontStuff.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def front_stuff_params
      params.require(:front_stuff).permit(:front)
    end
end

frontend/app/helpers/front_stuffs_helper.rb
module FrontStuffsHelper
end

frontend/app/views/front_stuffs/_form.html.erb
<%= form_for(@front_stuff) do |f| %>
  <% if @front_stuff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@front_stuff.errors.count, "error") %> prohibited this front_stuff from being saved:</h2>

      <ul>
      <% @front_stuff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :front %><br>
    <%= f.text_field :front %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

frontend/app/views/front_stuffs/edit.html.erb
<h1>Editing Front Stuff</h1>

<%= render 'form' %>

<%= link_to 'Show', @front_stuff %> |
<%= link_to 'Back', front_stuffs_path %>

frontend/app/views/front_stuffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Front Stuffs</h1>

<table>
  <thead>
    <tr>
      <th>Front</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @front_stuffs.each do |front_stuff| %>
      <tr>
        <td><%= front_stuff.front %></td>
        <td><%= link_to 'Show', front_stuff %></td>
        <td><%= link_to 'Edit', edit_front_stuff_path(front_stuff) %></td>
        <td><%= link_to 'Destroy', front_stuff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Front stuff', new_front_stuff_path %>

frontend/app/views/front_stuffs/new.html.erb
<h1>New Front Stuff</h1>

<%= render 'form' %>

<%= link_to 'Back', front_stuffs_path %>

frontend/app/views/front_stuffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Front:</strong>
  <%= @front_stuff.front %>
</p>

<%= link_to 'Edit', edit_front_stuff_path(@front_stuff) %> |
<%= link_to 'Back', front_stuffs_path %>